sonar.projectKey=tcc-devsecops-pipeline
sonar.projectName=TCC DevSecOps Pipeline
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=app
sonar.test.inclusions=app/test_*.py
sonar.exclusions=app/test_*.py,**/__pycache__/**,**/.pytest_cache/**,**/.venv/**,**/venv/**,**/.mypy_cache/**,**/.ruff_cache/**

sonar.sourceEncoding=UTF-8
sonar.python.version=3.12