apiVersion: v1
kind: Service
metadata:
  name: tcc-api
  namespace: app
  labels:
    app: tcc-api
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: tcc-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
